//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pilom.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Korzina = new HashSet<Korzina>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.ProductReviews = new HashSet<ProductReviews>();
            this.Stock = new HashSet<Stock>();
            this.SupplyDetails = new HashSet<SupplyDetails>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> WoodTypeID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Thickness { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public Nullable<int> StockQ { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korzina> Korzina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReviews> ProductReviews { get; set; }
        public virtual Units Units { get; set; }
        public virtual WoodTypes WoodTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyDetails> SupplyDetails { get; set; }
        public string CurrentPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(Image) || String.IsNullOrEmpty(Image))
                {
                    return "/Images/zagzag.jpg";
                }

                else
                {
                    return "/Images/" + Image;
                }
            }
        }
    }
}
