//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pilom.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplies()
        {
            this.SupplyDetails = new HashSet<SupplyDetails>();
        }
    
        public int SupplyID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyDetails> SupplyDetails { get; set; }
    }
}
