//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pilom.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyDetails
    {
        public int SupplyDetailID { get; set; }
        public Nullable<int> SupplyID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitCost { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Supplies Supplies { get; set; }
    }
}
